
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author Hossam Hamdy
 */
public class start extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();

        // The following code centers the form on the computer screen.
        // take a new object from Toolkit module.
        Toolkit toolkit = getToolkit();
        // get the screen dimension.
        Dimension size = toolkit.getScreenSize();
        // centerlize the frame in the screen.
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        projectLogo = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        privacy = new javax.swing.JButton();
        joyLogo = new javax.swing.JLabel();
        Fline = new javax.swing.JLabel();
        sLine = new javax.swing.JLabel();
        feedback = new javax.swing.JButton();
        darkMode = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java EStore Project: Welcome");
        setMaximumSize(new java.awt.Dimension(200, 0));

        startPanel.setBackground(new java.awt.Color(255, 255, 255));
        startPanel.setMaximumSize(new java.awt.Dimension(400, 400));
        startPanel.setLayout(null);

        projectLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Project Logo.png"))); // NOI18N
        startPanel.add(projectLogo);
        projectLogo.setBounds(10, 10, 640, 110);

        signin.setBackground(new java.awt.Color(0, 0, 0));
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/login.png"))); // NOI18N
        signin.setText("Sign In          ");
        signin.setToolTipText("Login to your account");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        startPanel.add(signin);
        signin.setBounds(20, 250, 220, 70);

        signup.setBackground(new java.awt.Color(0, 0, 0));
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/signup.png"))); // NOI18N
        signup.setText("Sign Up             ");
        signup.setToolTipText("Create a new account");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        startPanel.add(signup);
        signup.setBounds(20, 320, 220, 70);

        privacy.setBackground(new java.awt.Color(0, 0, 0));
        privacy.setForeground(new java.awt.Color(255, 255, 255));
        privacy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/privacy policy.png"))); // NOI18N
        privacy.setText("Privacy Policy");
        privacy.setToolTipText("Read privact policy.");
        privacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacyActionPerformed(evt);
            }
        });
        startPanel.add(privacy);
        privacy.setBounds(20, 390, 220, 70);

        joyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/joystic.png"))); // NOI18N
        startPanel.add(joyLogo);
        joyLogo.setBounds(370, 300, 410, 280);

        Fline.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Fline.setText("All your favorite games in one place.");
        startPanel.add(Fline);
        Fline.setBounds(20, 130, 490, 44);

        sLine.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        sLine.setText("Signup with us now to get 100$ as a gift.");
        startPanel.add(sLine);
        sLine.setBounds(20, 180, 590, 44);

        feedback.setBackground(new java.awt.Color(0, 0, 0));
        feedback.setForeground(new java.awt.Color(255, 255, 255));
        feedback.setText("Feedbacks");
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });
        startPanel.add(feedback);
        feedback.setBounds(20, 460, 220, 70);

        darkMode.setBackground(new java.awt.Color(0, 0, 0));
        darkMode.setForeground(new java.awt.Color(255, 255, 255));
        darkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Dark Mode Icon.png"))); // NOI18N
        darkMode.setText("Dark Mode Is OFF");
        darkMode.setToolTipText("Enable dark mode");
        darkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeActionPerformed(evt);
            }
        });
        startPanel.add(darkMode);
        darkMode.setBounds(20, 530, 220, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void darkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeActionPerformed
        // turn on/off dark mode
        int modeFlag = 0;   // if the modeFlag == 0 --> Dark mode is off
                            // if the modeFlag == 1 --> Dark mode is on.
        if(darkMode.isSelected()){
            startPanel.setBackground(new Color(120, 120, 120));
            darkMode.setText("Dark Mode Is ON");
            modeFlag = 1;
        }
        else{
            startPanel.setBackground(Color.white);
            darkMode.setText("Dark Mode Is OFF");
            modeFlag = 0;
        }
    }//GEN-LAST:event_darkModeActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // go to signin form
        signin signinForm = new signin();
        this.setVisible(false);
        signinForm.setVisible(true);
    }//GEN-LAST:event_signinActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void privacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privacyActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fline;
    private javax.swing.JToggleButton darkMode;
    private javax.swing.JButton feedback;
    private javax.swing.JLabel joyLogo;
    private javax.swing.JButton privacy;
    private javax.swing.JLabel projectLogo;
    private javax.swing.JLabel sLine;
    private javax.swing.JButton signin;
    private javax.swing.JButton signup;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
